"use client";

import { useState } from "react";
import { Course, CourseFormData, CourseFormErrors, CourseType } from "@/types/course";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { cn } from "@/lib/utils";
import { Plus, X } from "lucide-react";

interface AddCourseModalProps {
  isOpen: boolean;
  onClose: () => void;
  onAdd: (course: Course) => void;
}

export function AddCourseModal({
  isOpen,
  onClose,
  onAdd,
}: AddCourseModalProps) {
  const [formData, setFormData] = useState<CourseFormData>({
    title: "",
    type: "ONLINE",
    price: "",
    company: "",
    location: "",
    duration: "",
    rating: 5,
    description: "",
    startDate: "",
    endDate: "",
    maxStudents: 0,
    instructor: "",
    level: "Beginner",
  });

  const [errors, setErrors] = useState<CourseFormErrors>({});

  const courseTypes: { value: CourseType; label: string }[] = [
    { value: "ONLINE", label: "Online" },
    { value: "ONSITE", label: "On-site" },
    { value: "FULL-TIME", label: "Full-time" },
    { value: "PART-TIME", label: "Part-time" },
    { value: "HYBRID", label: "Hybrid" },
  ];

  const levels = [
    { value: "Beginner", label: "Beginner" },
    { value: "Intermediate", label: "Intermediate" },
    { value: "Advanced", label: "Advanced" },
  ];

  const validateForm = (): boolean => {
    const newErrors: CourseFormErrors = {};

    if (!formData.title.trim()) newErrors.title = "Title is required";
    if (!formData.company.trim()) newErrors.company = "Company is required";
    if (!formData.location.trim()) newErrors.location = "Location is required";
    if (!formData.duration.trim()) newErrors.duration = "Duration is required";
    if (!formData.price.trim()) newErrors.price = "Price is required";
    if (!formData.instructor?.trim())
      newErrors.instructor = "Instructor is required";
    if (formData.maxStudents && formData.maxStudents <= 0) {
      newErrors.maxStudents = "Max students must be greater than 0";
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    if (!validateForm()) return;

    const newCourse: Course = {
      id: Date.now(), // In real app, this would be generated by backend
      ...formData,
      rating: Number(formData.rating),
      maxStudents: formData.maxStudents || undefined,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    onAdd(newCourse);
    handleClose();
  };

  const handleClose = () => {
    setFormData({
      title: "",
      type: "ONLINE",
      price: "",
      company: "",
      location: "",
      duration: "",
      rating: 5,
      description: "",
      startDate: "",
      endDate: "",
      maxStudents: 0,
      instructor: "",
      level: "Beginner",
    });
    setErrors({});
    onClose();
  };

  const updateFormData = (field: keyof CourseFormData, value: any) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    if (errors[field]) {
      setErrors((prev) => ({ ...prev, [field]: undefined }));
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={handleClose}>
      <DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Plus className="h-5 w-5" />
            Add New Sponsored Course
          </DialogTitle>
          <DialogDescription>
            Create a new sponsored course for the platform. Fill in all required
            information below.
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-6">
          <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
            {/* Course Title */}
            <div className="md:col-span-2">
              <label className="text-foreground mb-2 block text-sm font-medium">
                Course Title *
              </label>
              <input
                type="text"
                value={formData.title}
                onChange={(e) => updateFormData("title", e.target.value)}
                className={cn(
                  "text-foreground bg-background w-full rounded-lg border px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary",
                  errors.title ? "border-destructive" : "border-border",
                )}
                placeholder="Enter course title"
              />
              {errors.title && (
                <p className="text-destructive mt-1 text-xs">{errors.title}</p>
              )}
            </div>

            {/* Course Type */}
            <div>
              <label className="text-foreground mb-2 block text-sm font-medium">
                Course Type *
              </label>
              <select
                value={formData.type}
                onChange={(e) =>
                  updateFormData("type", e.target.value as CourseType)
                }
                className="border-border bg-background text-foreground w-full rounded-lg border px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary"
              >
                {courseTypes.map((type) => (
                  <option key={type.value} value={type.value}>
                    {type.label}
                  </option>
                ))}
              </select>
            </div>

            {/* Level */}
            <div>
              <label className="text-foreground mb-2 block text-sm font-medium">
                Level *
              </label>
              <select
                value={formData.level}
                onChange={(e) => updateFormData("level", e.target.value)}
                className="border-border bg-background text-foreground w-full rounded-lg border px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary"
              >
                {levels.map((level) => (
                  <option key={level.value} value={level.value}>
                    {level.label}
                  </option>
                ))}
              </select>
            </div>

            {/* Company */}
            <div>
              <label className="text-foreground mb-2 block text-sm font-medium">
                Company *
              </label>
              <input
                type="text"
                value={formData.company}
                onChange={(e) => updateFormData("company", e.target.value)}
                className={cn(
                  "text-foreground bg-background w-full rounded-lg border px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary",
                  errors.company ? "border-destructive" : "border-border",
                )}
                placeholder="Enter company name"
              />
              {errors.company && (
                <p className="text-destructive mt-1 text-xs">
                  {errors.company}
                </p>
              )}
            </div>

            {/* Instructor */}
            <div>
              <label className="text-foreground mb-2 block text-sm font-medium">
                Instructor *
              </label>
              <input
                type="text"
                value={formData.instructor}
                onChange={(e) => updateFormData("instructor", e.target.value)}
                className={cn(
                  "text-foreground bg-background w-full rounded-lg border px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary",
                  errors.instructor ? "border-destructive" : "border-border",
                )}
                placeholder="Enter instructor name"
              />
              {errors.instructor && (
                <p className="text-destructive mt-1 text-xs">
                  {errors.instructor}
                </p>
              )}
            </div>

            {/* Location */}
            <div>
              <label className="text-foreground mb-2 block text-sm font-medium">
                Location *
              </label>
              <input
                type="text"
                value={formData.location}
                onChange={(e) => updateFormData("location", e.target.value)}
                className={cn(
                  "text-foreground bg-background w-full rounded-lg border px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary",
                  errors.location ? "border-destructive" : "border-border",
                )}
                placeholder="Enter location"
              />
              {errors.location && (
                <p className="text-destructive mt-1 text-xs">
                  {errors.location}
                </p>
              )}
            </div>

            {/* Duration */}
            <div>
              <label className="text-foreground mb-2 block text-sm font-medium">
                Duration *
              </label>
              <input
                type="text"
                value={formData.duration}
                onChange={(e) => updateFormData("duration", e.target.value)}
                className={cn(
                  "text-foreground bg-background w-full rounded-lg border px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary",
                  errors.duration ? "border-destructive" : "border-border",
                )}
                placeholder="e.g., 3 months, 12 weeks"
              />
              {errors.duration && (
                <p className="text-destructive mt-1 text-xs">
                  {errors.duration}
                </p>
              )}
            </div>

            {/* Price */}
            <div>
              <label className="text-foreground mb-2 block text-sm font-medium">
                Price *
              </label>
              <input
                type="text"
                value={formData.price}
                onChange={(e) => updateFormData("price", e.target.value)}
                className={cn(
                  "text-foreground bg-background w-full rounded-lg border px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary",
                  errors.price ? "border-destructive" : "border-border",
                )}
                placeholder="e.g., DZD 25,000"
              />
              {errors.price && (
                <p className="text-destructive mt-1 text-xs">{errors.price}</p>
              )}
            </div>

            {/* Max Students */}
            <div>
              <label className="text-foreground mb-2 block text-sm font-medium">
                Max Students
              </label>
              <input
                type="number"
                value={formData.maxStudents}
                onChange={(e) =>
                  updateFormData("maxStudents", parseInt(e.target.value) || 0)
                }
                className="border-border bg-background text-foreground w-full rounded-lg border px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary"
                placeholder="Enter maximum students"
                min="1"
              />
              {errors.maxStudents && (
                <p className="text-destructive mt-1 text-xs">
                  {errors.maxStudents}
                </p>
              )}
            </div>

            {/* Rating */}
            <div>
              <label className="text-foreground mb-2 block text-sm font-medium">
                Rating
              </label>
              <select
                value={formData.rating}
                onChange={(e) =>
                  updateFormData("rating", parseInt(e.target.value))
                }
                className="border-border bg-background text-foreground w-full rounded-lg border px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary"
              >
                {[1, 2, 3, 4, 5].map((rating) => (
                  <option key={rating} value={rating}>
                    {rating} Star{rating > 1 ? "s" : ""}
                  </option>
                ))}
              </select>
            </div>

            {/* Start Date */}
            <div>
              <label className="text-foreground mb-2 block text-sm font-medium">
                Start Date
              </label>
              <input
                type="date"
                value={formData.startDate}
                onChange={(e) => updateFormData("startDate", e.target.value)}
                className="border-border bg-background text-foreground w-full rounded-lg border px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary"
              />
            </div>

            {/* End Date */}
            <div>
              <label className="text-foreground mb-2 block text-sm font-medium">
                End Date
              </label>
              <input
                type="date"
                value={formData.endDate}
                onChange={(e) => updateFormData("endDate", e.target.value)}
                className="border-border bg-background text-foreground w-full rounded-lg border px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary"
              />
            </div>
          </div>

          {/* Description */}
          <div>
            <label className="text-foreground mb-2 block text-sm font-medium">
              Description
            </label>
            <textarea
              value={formData.description}
              onChange={(e) => updateFormData("description", e.target.value)}
              rows={3}
              className="border-border bg-background text-foreground w-full rounded-lg border px-3 py-2 focus:outline-none focus:ring-2 focus:ring-primary"
              placeholder="Enter course description"
            />
          </div>

          <DialogFooter className="gap-2">
            <Button type="button" variant="outline" onClick={handleClose}>
              <X className="mr-2 h-4 w-4" />
              Cancel
            </Button>
            <Button
              type="submit"
              className="hover:bg-primary-button bg-primary"
            >
              <Plus className="mr-2 h-4 w-4" />
              Add Course
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
